"""卡牌行为期望表（独立 oracle）。

每条 CardExpectation 是一张卡的机制级期望结果，标准答案来源标在 source 字段
（STS wiki / 社区 / 实机轨迹），绝不取被测模拟器自己的数字。

当前为地基骨架，仅含起始三卡；全量 Ironclad + 无色卡分批补（另起计划）。
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional

from v8.backends.combat_probe import CombatSetup


@dataclass(frozen=True)
class CardExpectation:
    card_id: str
    # 场景标签（同一张卡多场景时区分）；空则显示 card_id。kw_only 让它声明在
    # card_id 之后又不强制后续 setup/target_index 带默认值。
    label: str = field(default="", kw_only=True)
    setup: CombatSetup
    target_index: int                                    # 敌人 idx；<0 = 自我
    expect_enemy_hp_delta: Optional[int] = None
    expect_player_block_delta: Optional[int] = None
    expect_energy_delta: Optional[int] = None
    expect_enemy_status: Optional[Dict[str, int]] = None  # 子集匹配
    expect_player_status: Optional[Dict[str, int]] = None  # 子集匹配（玩家自身状态）
    expect_all_enemies_hp_delta: Optional[int] = None      # 每个敌人都应掉这么多
    expect_all_enemies_status: Optional[Dict[str, int]] = None  # 每个敌人都应有这些状态（子集匹配）
    source: str = ""                                      # 标准答案出处


ORACLE: List[CardExpectation] = [
    CardExpectation(
        card_id="Strike_R",
        setup=CombatSetup(hand=("Strike_R",)),
        target_index=0,
        expect_enemy_hp_delta=6,
        expect_energy_delta=1,
        source="STS wiki: Strike deals 6 damage (cost 1)",
    ),
    CardExpectation(
        card_id="Defend_R",
        setup=CombatSetup(hand=("Defend_R",)),
        target_index=-1,
        expect_player_block_delta=5,
        expect_energy_delta=1,
        source="STS wiki: Defend gains 5 Block (cost 1)",
    ),
    CardExpectation(
        card_id="Bash",
        setup=CombatSetup(hand=("Bash",)),
        target_index=0,
        expect_enemy_hp_delta=8,
        expect_energy_delta=2,
        expect_enemy_status={"Vulnerable": 2},
        source="STS wiki: Bash deals 8 damage + 2 Vulnerable (cost 2)",
    ),
    CardExpectation(
        card_id="Anger",
        setup=CombatSetup(hand=("Anger",)),
        target_index=0,
        expect_enemy_hp_delta=6,
        expect_energy_delta=0,
        source="STS wiki: Anger 0-cost, 6 damage (also adds a copy to discard — not asserted here)",
    ),
    CardExpectation(
        card_id="Clothesline",
        setup=CombatSetup(hand=("Clothesline",)),
        target_index=0,
        expect_enemy_hp_delta=12,
        expect_energy_delta=2,
        expect_enemy_status={"Weakened": 2},
        source="STS wiki: Clothesline 2-cost, 12 damage + 2 Weak",
    ),
    CardExpectation(
        card_id="Twin Strike",
        setup=CombatSetup(hand=("Twin Strike",)),
        target_index=0,
        expect_enemy_hp_delta=10,
        expect_energy_delta=1,
        source="STS wiki: Twin Strike 5 damage x2 = 10",
    ),
    CardExpectation(
        card_id="Thunderclap",
        setup=CombatSetup(hand=("Thunderclap",)),
        target_index=0,
        expect_enemy_hp_delta=4,
        expect_energy_delta=1,
        expect_enemy_status={"Vulnerable": 1},
        source="STS wiki: Thunderclap 4 damage + 1 Vulnerable to ALL (single-enemy slice here)",
    ),
    CardExpectation(
        card_id="Iron Wave",
        setup=CombatSetup(hand=("Iron Wave",)),
        target_index=0,
        expect_enemy_hp_delta=5,
        expect_player_block_delta=5,
        expect_energy_delta=1,
        source="STS wiki: Iron Wave 5 block + 5 damage",
    ),
    CardExpectation(
        card_id="Pommel Strike",
        setup=CombatSetup(hand=("Pommel Strike",)),
        target_index=0,
        expect_enemy_hp_delta=9,
        expect_energy_delta=1,
        source="STS wiki: Pommel Strike 9 damage + draw 1 (draw not asserted)",
    ),
    CardExpectation(
        card_id="Shrug It Off",
        setup=CombatSetup(hand=("Shrug It Off",)),
        target_index=-1,
        expect_enemy_hp_delta=0,
        expect_player_block_delta=8,
        expect_energy_delta=1,
        source="STS wiki: Shrug It Off 8 block + draw 1 (draw not asserted)",
    ),
    CardExpectation(
        card_id="Inflame",
        setup=CombatSetup(hand=("Inflame",)),
        target_index=-1,
        expect_enemy_hp_delta=0,
        expect_player_block_delta=0,
        expect_player_status={"Strength": 2},
        expect_energy_delta=1,
        source="STS wiki: Inflame power, +2 Strength",
    ),
    # ---- 力量注入对照：证明 player_strength 注入真生效 ----
    CardExpectation(
        card_id="Strike_R",
        label="Strike_R (+3 Str control)",
        setup=CombatSetup(hand=("Strike_R",), player_strength=3),
        target_index=0,
        expect_enemy_hp_delta=9,   # 6 基础 + 3 力量
        expect_energy_delta=1,
        source="STS: Strike 6 + Strength 3 = 9（力量注入对照）",
    ),
    # ---- Body Slam：伤害=当前格挡，力量加性不是乘性，且不消耗格挡 ----
    CardExpectation(
        card_id="Body Slam",
        label="Body Slam (10 block)",
        setup=CombatSetup(hand=("Body Slam",), player_block=10, player_strength=0),
        target_index=0,
        expect_enemy_hp_delta=10,
        expect_player_block_delta=0,
        expect_energy_delta=1,
        source="STS wiki: Body Slam damage = current Block(10); block not consumed",
    ),
    CardExpectation(
        card_id="Body Slam",
        label="Body Slam (10 block +3 Str)",
        setup=CombatSetup(hand=("Body Slam",), player_block=10, player_strength=3),
        target_index=0,
        expect_enemy_hp_delta=13,
        expect_energy_delta=1,
        source="STS wiki: Body Slam = Block + Strength additive = 13",
    ),
    CardExpectation(
        card_id="Body Slam",
        label="Body Slam (0 block +5 Str)",
        setup=CombatSetup(hand=("Body Slam",), player_block=0, player_strength=5),
        target_index=0,
        expect_enemy_hp_delta=5,
        expect_energy_delta=1,
        source="STS wiki: Body Slam 0 block + 5 Str = 5",
    ),
    # ---- Heavy Blade：基础 14，力量×3 倍率，cost 2 ----
    CardExpectation(
        card_id="Heavy Blade",
        label="Heavy Blade (0 Str)",
        setup=CombatSetup(hand=("Heavy Blade",), player_strength=0),
        target_index=0,
        expect_enemy_hp_delta=14,
        expect_energy_delta=2,
        source="STS wiki: Heavy Blade base 14",
    ),
    CardExpectation(
        card_id="Heavy Blade",
        label="Heavy Blade (+3 Str)",
        setup=CombatSetup(hand=("Heavy Blade",), player_strength=3),
        target_index=0,
        expect_enemy_hp_delta=23,   # 14 + 3×3
        expect_energy_delta=2,
        source="STS wiki: Heavy Blade 14 + Strength×3 = 23",
    ),
    CardExpectation(
        card_id="Heavy Blade",
        label="Heavy Blade (-2 Str)",
        setup=CombatSetup(hand=("Heavy Blade",), player_strength=-2),
        target_index=0,
        expect_enemy_hp_delta=8,    # 14 + (-2)×3
        expect_energy_delta=2,
        source="STS wiki: Heavy Blade 14 + (-2)×3 = 8",
    ),    # ===== 第二轮：38 张可测卡 baseline（none / strength_or_block_setup，剔除已在表内）=====
    CardExpectation(
        card_id='Flex',
        setup=CombatSetup(hand=('Flex',)),
        target_index=-1,
        expect_enemy_hp_delta=0,
        expect_player_status={'Strength': 2},
        expect_energy_delta=0,
        source='https://slaythespire.wiki.gg/wiki/Flex',
    ),
    CardExpectation(
        card_id='Carnage',
        setup=CombatSetup(hand=('Carnage',)),
        target_index=0,
        expect_enemy_hp_delta=20,
        expect_energy_delta=2,
        source='https://slaythespire.wiki.gg/wiki/Carnage',
    ),
    CardExpectation(
        card_id='Dropkick',
        setup=CombatSetup(hand=('Dropkick',)),
        target_index=0,
        expect_enemy_hp_delta=5,
        expect_energy_delta=1,
        source='https://slaythespire.wiki.gg/wiki/Dropkick',
    ),
    CardExpectation(
        card_id='Hemokinesis',
        setup=CombatSetup(hand=('Hemokinesis',)),
        target_index=0,
        expect_enemy_hp_delta=15,
        expect_energy_delta=1,
        source='https://slaythespire.wiki.gg/wiki/Hemokinesis',
    ),
    CardExpectation(
        card_id='Pummel',
        setup=CombatSetup(hand=('Pummel',)),
        target_index=0,
        expect_enemy_hp_delta=8,
        expect_energy_delta=1,
        source='https://slaythespire.wiki.gg/wiki/Pummel',
    ),
    CardExpectation(
        card_id='Searing Blow',
        setup=CombatSetup(hand=('Searing Blow',)),
        target_index=0,
        expect_enemy_hp_delta=12,
        expect_energy_delta=2,
        source='https://slaythespire.wiki.gg/wiki/Searing_Blow',
    ),
    CardExpectation(
        card_id='Uppercut',
        setup=CombatSetup(hand=('Uppercut',)),
        target_index=0,
        expect_enemy_hp_delta=13,
        expect_enemy_status={'Vulnerable': 1, 'Weakened': 1},
        expect_energy_delta=2,
        source='https://slaythespire.wiki.gg/wiki/Uppercut',
    ),
    CardExpectation(
        card_id='Battle Trance',
        setup=CombatSetup(hand=('Battle Trance',)),
        target_index=-1,
        expect_enemy_hp_delta=0,
        expect_player_status={'NoDraw': 1},
        expect_energy_delta=0,
        source='https://slaythespire.wiki.gg/wiki/Battle_Trance',
    ),
    CardExpectation(
        card_id='Bloodletting',
        setup=CombatSetup(hand=('Bloodletting',)),
        target_index=-1,
        expect_enemy_hp_delta=0,
        source='https://slaythespire.wiki.gg/wiki/Bloodletting',
    ),
    CardExpectation(
        card_id='Disarm',
        setup=CombatSetup(hand=('Disarm',)),
        target_index=0,
        expect_enemy_hp_delta=0,
        expect_enemy_status={'Strength': -2},
        expect_energy_delta=1,
        source='https://slaythespire.wiki.gg/wiki/Disarm',
    ),
    CardExpectation(
        card_id='Entrench',
        setup=CombatSetup(hand=('Entrench',)),
        target_index=-1,
        expect_enemy_hp_delta=0,
        expect_energy_delta=2,
        source='https://slaythespire.wiki.gg/wiki/Entrench',
    ),
    CardExpectation(
        card_id='Ghostly Armor',
        setup=CombatSetup(hand=('Ghostly Armor',)),
        target_index=-1,
        expect_enemy_hp_delta=0,
        expect_player_block_delta=10,
        expect_energy_delta=1,
        source='https://slaythespire.wiki.gg/wiki/Ghostly_Armor',
    ),
    CardExpectation(
        card_id='Seeing Red',
        setup=CombatSetup(hand=('Seeing Red',)),
        target_index=-1,
        expect_enemy_hp_delta=0,
        source='https://slaythespire.wiki.gg/wiki/Seeing_Red',
    ),
    CardExpectation(
        card_id='Bludgeon',
        setup=CombatSetup(hand=('Bludgeon',)),
        target_index=0,
        expect_enemy_hp_delta=32,
        expect_energy_delta=3,
        source='https://slaythespire.wiki.gg/wiki/Bludgeon',
    ),
    CardExpectation(
        card_id='Feed',
        setup=CombatSetup(hand=('Feed',)),
        target_index=0,
        expect_enemy_hp_delta=10,
        expect_energy_delta=1,
        source='https://slaythespire.wiki.gg/wiki/Feed',
    ),
    CardExpectation(
        card_id='Impervious',
        setup=CombatSetup(hand=('Impervious',)),
        target_index=-1,
        expect_enemy_hp_delta=0,
        expect_player_block_delta=30,
        expect_energy_delta=2,
        source='https://slaythespire.wiki.gg/wiki/Impervious',
    ),
    CardExpectation(
        card_id='Limit Break',
        setup=CombatSetup(hand=('Limit Break',)),
        target_index=-1,
        expect_enemy_hp_delta=0,
        expect_energy_delta=1,
        source='https://slaythespire.wiki.gg/wiki/Limit_Break',
    ),
    CardExpectation(
        card_id='Barricade',
        setup=CombatSetup(hand=('Barricade',)),
        target_index=-1,
        expect_enemy_hp_delta=0,
        expect_player_status={'Barricade': 1},
        expect_energy_delta=3,
        source='https://slaythespire.wiki.gg/wiki/Barricade',
    ),
    CardExpectation(
        card_id='Berserk',
        setup=CombatSetup(hand=('Berserk',)),
        target_index=-1,
        expect_enemy_hp_delta=0,
        expect_player_status={'Vulnerable': 2, 'Berserk': 1},
        expect_energy_delta=0,
        source='https://slaythespire.wiki.gg/wiki/Berserk',
    ),
    CardExpectation(
        card_id='Juggernaut',
        setup=CombatSetup(hand=('Juggernaut',)),
        target_index=-1,
        expect_enemy_hp_delta=0,
        expect_energy_delta=2,
        source='https://slaythespire.wiki.gg/wiki/Juggernaut',
    ),
    CardExpectation(
        card_id='Blind',
        setup=CombatSetup(hand=('Blind',)),
        target_index=0,
        expect_enemy_hp_delta=0,
        expect_enemy_status={'Weakened': 2},
        expect_energy_delta=0,
        source='https://slaythespire.wiki.gg/wiki/Blind',
    ),
    CardExpectation(
        card_id='Dark Shackles',
        setup=CombatSetup(hand=('Dark Shackles',)),
        target_index=0,
        expect_enemy_hp_delta=0,
        expect_enemy_status={'Shackled': 9},
        expect_energy_delta=0,
        source='https://slaythespire.wiki.gg/wiki/Dark_Shackles',
    ),
    CardExpectation(
        card_id='Finesse',
        setup=CombatSetup(hand=('Finesse',)),
        target_index=-1,
        expect_enemy_hp_delta=0,
        expect_player_block_delta=2,
        expect_energy_delta=0,
        source='https://slaythespire.wiki.gg/wiki/Finesse',
    ),
    CardExpectation(
        card_id='Flash of Steel',
        setup=CombatSetup(hand=('Flash of Steel',)),
        target_index=0,
        expect_enemy_hp_delta=3,
        expect_energy_delta=0,
        source='https://slaythespire.wiki.gg/wiki/Flash_of_Steel',
    ),
    CardExpectation(
        card_id='Good Instincts',
        setup=CombatSetup(hand=('Good Instincts',)),
        target_index=-1,
        expect_enemy_hp_delta=0,
        expect_player_block_delta=6,
        expect_energy_delta=0,
        source='https://slaythespire.wiki.gg/wiki/Good_Instincts',
    ),
    CardExpectation(
        card_id='Panacea',
        setup=CombatSetup(hand=('Panacea',)),
        target_index=-1,
        expect_enemy_hp_delta=0,
        expect_player_status={'Artifact': 1},
        expect_energy_delta=0,
        source='https://slaythespire.wiki.gg/wiki/Panacea',
    ),
    CardExpectation(
        card_id='PanicButton',
        setup=CombatSetup(hand=('PanicButton',)),
        target_index=-1,
        expect_enemy_hp_delta=0,
        expect_player_block_delta=30,
        expect_player_status={'No Block': 2},
        expect_energy_delta=0,
        source='https://slaythespire.wiki.gg/wiki/Panic_Button',
    ),
    CardExpectation(
        card_id='Swift Strike',
        setup=CombatSetup(hand=('Swift Strike',)),
        target_index=0,
        expect_enemy_hp_delta=7,
        expect_energy_delta=0,
        source='https://slaythespire.wiki.gg/wiki/Swift_Strike',
    ),
    CardExpectation(
        card_id='Trip',
        setup=CombatSetup(hand=('Trip',)),
        target_index=0,
        expect_enemy_hp_delta=0,
        expect_enemy_status={'Vulnerable': 2},
        expect_energy_delta=0,
        source='https://slaythespire.wiki.gg/wiki/Trip',
    ),
    CardExpectation(
        card_id='Bite',
        setup=CombatSetup(hand=('Bite',)),
        target_index=0,
        expect_enemy_hp_delta=7,
        expect_energy_delta=1,
        source='https://slaythespire.wiki.gg/wiki/Bite',
    ),
    CardExpectation(
        card_id='J.A.X.',
        setup=CombatSetup(hand=('J.A.X.',)),
        target_index=-1,
        expect_enemy_hp_delta=0,
        expect_player_status={'Strength': 2},
        expect_energy_delta=0,
        source='https://slaythespire.wiki.gg/wiki/J.A.X.',
    ),
    # ===== 第三轮：multi_enemy AoE 卡（enemy_count=3 验全体）=====
    # 固定全体伤害 / debuff 卡
    CardExpectation(
        card_id='Cleave',
        label='Cleave AoE',
        setup=CombatSetup(hand=('Cleave',), enemy_count=3),
        target_index=0,
        expect_all_enemies_hp_delta=8,
        expect_energy_delta=1,
        source='https://slaythespire.wiki.gg/wiki/Cleave (AoE 8 to all)',
    ),
    CardExpectation(
        card_id='Thunderclap',
        label='Thunderclap AoE',
        setup=CombatSetup(hand=('Thunderclap',), enemy_count=3),
        target_index=0,
        expect_all_enemies_hp_delta=4,
        expect_all_enemies_status={'Vulnerable': 1},
        expect_energy_delta=1,
        source='https://slaythespire.wiki.gg/wiki/Thunderclap (AoE 4 + 1 Vulnerable to all)',
    ),
    CardExpectation(
        card_id='Intimidate',
        label='Intimidate AoE',
        setup=CombatSetup(hand=('Intimidate',), enemy_count=3),
        target_index=0,
        expect_all_enemies_hp_delta=0,
        expect_all_enemies_status={'Weakened': 1},
        expect_energy_delta=0,
        source='https://slaythespire.wiki.gg/wiki/Intimidate (AoE 1 Weak to all, exhaust)',
    ),
    CardExpectation(
        card_id='Shockwave',
        label='Shockwave AoE',
        setup=CombatSetup(hand=('Shockwave',), enemy_count=3),
        target_index=0,
        expect_all_enemies_hp_delta=0,
        expect_all_enemies_status={'Weakened': 3, 'Vulnerable': 3},
        expect_energy_delta=2,
        source='https://slaythespire.wiki.gg/wiki/Shockwave (cost 2; AoE 3 Weak + 3 Vulnerable to all, exhaust)',
    ),
    CardExpectation(
        card_id='Immolate',
        label='Immolate AoE',
        setup=CombatSetup(hand=('Immolate',), enemy_count=3),
        target_index=0,
        expect_all_enemies_hp_delta=21,
        expect_energy_delta=2,
        source='https://slaythespire.wiki.gg/wiki/Immolate (AoE 21 to all + Burn to discard)',
    ),
    CardExpectation(
        card_id='Reaper',
        label='Reaper AoE',
        setup=CombatSetup(hand=('Reaper',), enemy_count=3),
        target_index=0,
        expect_all_enemies_hp_delta=4,
        expect_energy_delta=2,
        source='https://slaythespire.wiki.gg/wiki/Reaper (AoE 4 to all + lifesteal, exhaust)',
    ),
    CardExpectation(
        card_id='Dramatic Entrance',
        label='Dramatic Entrance AoE',
        setup=CombatSetup(hand=('Dramatic Entrance',), enemy_count=3),
        target_index=0,
        expect_all_enemies_hp_delta=8,
        expect_energy_delta=0,
        source='https://slaythespire.wiki.gg/wiki/Dramatic_Entrance (AoE 8 to all, exhaust)',
    ),
    # 随机分配伤害卡：多敌不可逐敌确定性断言，改用 enemy_count=1 验单敌总伤
    CardExpectation(
        card_id='Sword Boomerang',
        label='Sword Boomerang (single-enemy, 随机分配仅单敌可确定测)',
        setup=CombatSetup(hand=('Sword Boomerang',), enemy_count=1),
        target_index=0,
        expect_enemy_hp_delta=9,
        expect_energy_delta=1,
        source='https://slaythespire.wiki.gg/wiki/Sword_Boomerang (3x3 random target; single enemy all hits land = 9)',
    ),
]
